### ISSUE TITLE
Befehle kommen scheinbar nicht an (HmIP)

### ISSUE THREAD

**Issue by widder** [danielperna84/pyhomematic#106]
**Description of problem:**

Ist nur die CCU am laufen, verhält sich der HmIP-WRC2 Taster ganz normal (einmal orange blinken, dann grün).
Startet man Home Assistant und fügt man eine Automation hinzu, welche über den 
Taster einen einzigen Schaltaktor einschaltet, ist weiterhin alles normal (einmal orange blinken, dann grün)
Sobald ich eine Automation erstelle, die mehr als 2 Schaltaktoren einschaltet, verhält sich der Wandtaster auffällig: der Schalter blinkt mehrere Sekunden lang orange, dann rot. Laut Taster-Bedienungsanleitung bedeutet das, dass der Befehl nicht ankam.

Der Befehl kommt aber definitiv an den Aktoren an.

Ich bin mir unsicher, ob das ein Bug in pyhomematic oder Home Asisstant selbst ist oder weder noch.

**Traceback or log (if applicable):**
```bash
2017-12-30 13:10:54 DEBUG (Thread-22) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 00018314AC52ED:2, value_key = PRESS_SHORT, value = True
2017-12-30 13:10:54 INFO (Thread-22) [pyhomematic.devicetypes.generic] HMGeneric.event: address=00018314AC52ED:2, interface_id=homeassistant-ip, key=PRESS_SHORT, value=True
2017-12-30 13:10:54 DEBUG (Thread-22) [pyhomematic.devicetypes.generic] HMDevice.event: Using callback functools.partial(<function _hm_event_handler at 0x6c52b588>, <homeassistant.core.HomeAssistant object at 0x7642fa10>, 'ip') 
2017-12-30 13:10:54 DEBUG (Thread-22) [homeassistant.components.homematic] Event PRESS_SHORT for 00018314AC52ED channel 2
2017-12-30 13:10:54 INFO (MainThread) [homeassistant.core] Bus:Handling <Event homematic.keypress[L]: name=00018314AC52ED, param=PRESS_SHORT, channel=2>
2017-12-30 13:10:54 INFO (MainThread) [homeassistant.components.automation] Executing Lichtschalter
2017-12-30 13:10:54 INFO (MainThread) [homeassistant.core] Bus:Handling <Event logbook_entry[L]: entity_id=automation.lichtschalter, name=Lichtschalter, message=has been triggered, domain=automation>
2017-12-30 13:10:54 INFO (MainThread) [homeassistant.helpers.script] Script Lichtschalter: Running script
2017-12-30 13:10:54 INFO (MainThread) [homeassistant.helpers.script] Script Lichtschalter: Executing step call service
2017-12-30 13:10:54 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service=turn_on, domain=switch, service_call_id=1974344688-9, service_data=entity_id=['group.gaestezimmer']>
```

_If you encounter the problem when using Home Assistant, please fill out the following information_

**Home Assistant version (if applicable):**
0.60.0

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**

in automations.yaml

```yaml
- id: lichtschalter
  alias: "Lichtschalter"
  hide_entity: True
  trigger:
    platform: event
    event_type: homematic.keypress
    event_data:
      name: "00018314AC52ED"
      channel: 1
      param: PRESS_SHORT
  action:
    - service: switch.turn_on
      entity_id: switch.schalter1
    - service: switch.turn_on
      entity_id: switch.schalter2
    - service: switch.turn_on
      entity_id: switch.schalter3
```
(hier mit mehreren Aktionen statt Gruppe, wollte jetzt nicht das Issue zumüllen)

1. Eine Automation hinzufügen, die mit einem HmIP-Taster einen Aktor schaltet -> funktioniert normal
1. Eine Automation hinzufügen, die mit einem HmIP-Taster mehrere Aktoren bzw. eine Gruppe schaltet -> Taster verhält sich fehlerhaft
3. Sobald mehrere Aktionen da sind, wird der Taster orange blinken und anschließend rot und reagiert währenddessen nicht auf Eingaben.

Falls weitere Logeinträge nötig sind, kann ich die gerne nachreichen.

**Comment by danielperna84** [comment]
Das klingt in der Tat ziemlich merkwürdig. Um es einzugrenzen würde ich, wenn möglich, mal folgendes versuchen: Anstatt Aktoren zu steuern einfach mal 3 [input_boolean](https://home-assistant.io/components/input_boolean/) variablen erstellen und alle drei mit einer Automation per Fernbedienung einschalten. Wenn das ohne weiteres geht, dann ist es ggf. ein Performance-Problem. Die Inputs sind ja nur intern und sollten ruck-zuck umschalten.

Meine Vermutung wäre, dass die Fernbedienung auf ein "hat alles geklappt" von der CCU wartet, dass aber nicht in dem nötigen Zeitraum ankommt. Wenn das Signal (Event der Fernbedienung) erst von der CCU zu Home Assistant muss, von dort dann mehrere Signale (systembedignt nacheinander) wieder zur CCU, die die Aktoren schaltet, dafür dann die "hat geklappt" Meldungen zurück zur CCU, ja, das dauert einen Moment. Wobei man bei der XML-RPC API eigentlich keine Antworten auf Events schickt. Die CCU sagt immer nur "das ist passiert". Wäre mir neu, dass sie auf ein "hab verstanden" wartet.

**Comment by widder** [comment]
Ja, mit input_boolean klappt es.
Ich steuere über Homegear 3 Intertechno-Aktoren. Mit nur einem geht es ohne Probleme. Möglicherweise liegt es daran, denn die werden ja nicht gleichzeitig eingeschaltet sondern nacheinander, das dauert.

**Comment by danielperna84** [comment]
Ich würde folgendes mal probieren:
Erstelle ein Script, welches die ganzen Aktoren betätigt. Und mit dem Event von der Fernbedienung schaltest Du einfach das Script ein. Könnte mir vorstellen, dass das besser klappt, denn das Script sollte ja sofort ausgeführt werden. Und die Aktoren können ja z.B. mit einer Verzögerung eingeschaltet werden.

**Comment by widder** [comment]
Mit einem Script geht es tatsächlich. Es ist nicht mal ein `delay` nötig.
Vielen Dank.

**Comment by danielperna84** [comment]
Super. So haben wir ja nun einen Workaround. Dann schließe ich das hier mal. :)

**Comment by Gomez** [comment]
@widder Wie sieht das yml bei dir genau aus. Ich habe glaub das gleiche Problem, aber so recht will es noch nicht

**Comment by widder** [comment]
**Falls noch jemand auf das Issue hier stößt: Ich kann derzeit niemandem empfehlen Homematic-Fernbedienungen zu kaufen, um sie auf diese Weise zu verwenden! Das ganze funktioniert noch nicht gut genug!**

Inzwischen schalte ich mit der Fernbedienung Zigbee-Lampen. Das ist sogar noch problematischer als Intertechno. Da hilft das Delay bedingt bis gar nicht.

Gut wäre eine Option in pyhomematic, womit man einstellen kann, dass es mir egal ist, ob die Befehle rechtzeitig ankommen.

Wie auch immer hier sind meine alten Scripts, die ganz gut mit Intertechno/Homegear funktionierten:


scripts.yaml:

```yaml
multi_on:
  sequence:
    - delay:
        milliseconds: 100
    - service: switch.turn_on
      entity_id: switch.A1
    - delay:
        milliseconds: 80
    - service: switch.turn_on
      entity_id: switch.A2

multi_off:
  sequence:
    - delay:
        milliseconds: 100
    - service: switch.turn_off
      entity_id: switch.A1
    - delay:
        milliseconds: 80
    - service: switch.turn_off
      entity_id: switch.A2
```

automations.yaml

```yaml
- alias: "Multi an"
  hide_entity: True
  trigger:
    platform: event
    event_type: homematic.keypress
    event_data:
      name: "NEQ0135291"
      channel: 2
      param: PRESS_SHORT
  action:
    service: script.turn_on
    entity_id: script.multi_off

- alias: "Multi aus"
  hide_entity: True
  trigger:
    platform: event
    event_type: homematic.keypress
    event_data:
      name: "NEQ0135291"
      channel: 1
      param: PRESS_SHORT
  action:
    service: script.turn_on
    entity_id: script.multi_on
```
