### ISSUE TITLE
Resolvenames with json does not work

### ISSUE THREAD

**Issue by speedmann** [danielperna84/pyhomematic#224]
**Home Assistant version (if applicable):**
0.87.1
** Raspberrymatic Version:**
3.41.11.20190126

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml
homematic:
  interfaces:
    rf:
      host: homematic-raspi.swapoff.de
      resolvenames: json
      port: 2001
      username: !secret user
      password: !secret password
    ip:
      host: homematic-raspi.swapoff.de
      port: 2010
      jsonport: 80
      resolvenames: json
      username: !secret user
      password: !secret password
```

Use the following configuration for debug-output of the related components:
```yaml
logs:
  homeassistant.components.homematic: debug
  pyhomematic: debug
```

**Describe the bug**
Names of homematic devices are not fetched from the CCUv3

**To Reproduce**
1. Configure home assistant like described
2. start home assistant
3. wait for startup
4. See homematic devices with serial number as their `friendly_name` 

**Expected behavior**
Have the names defined in ccu show up as friendly names

**Additional context**

I dug into the code and figured out pyhomematic does get a list of all interfaces the ccu knows of. 
Then it loops over the list and checks if any interface matches the port configured in home-assistant (which is 2001 or 2010 in my case).
The response from homematic includes different ports though.

```
2019-02-18 12:15:09 ERROR (Thread-3) [pyhomematic._hm] {'id': 0, 'version': '1.1', 'result': [{'name': 'BidCos-RF', 'port': 32001, 'info': 'BidCos-RF'}, {'name': 'VirtualDevices', 'port': 39292, 'info': 'Virtual Devices'}, {'name': 'HmIP-RF', 'port': 32010, 'info': 'HmIP-RF'}], 'error': None}
```

I did some more research to find out what these ports are. Reffering to the developer, they are "for internal use (127.0.0.1) only.

Changeing home assistant to use ports 32001 and 32010 fails, because these ports are not opened to remote systems.

I did hack around in _hm.py:366 and added '3' to the if statement, which works but can't be a good solution.

Some mor edetails can be found here (german only, unfortunately)
https://homematic-forum.de/forum/viewtopic.php?f=26&t=46448&start=40#p465430
