### ISSUE TITLE
transition time for homematic dimmer

### ISSUE THREAD

**Issue by trilu2000** [danielperna84/pyhomematic#236]
Request is regards adding transition time for homematic lightcontrollers

The homeassistant light.turn_on service gives the option to pass some parameter to a light controller device -i would appreciate if the transition attribute would work.

Happy to support ...

**Comment by danielperna84** [comment]
I'm 99% sure you can already set the transition time by using the [homematic.put_paramset](https://www.home-assistant.io/components/homematic/#services).
And I'm also pretty sure it's technically not possible to modify the transition time __AND__ control the light with one call to the API. The `setValue` method only takes one parameter (of the `VALUES` paramset), and the parameter for the transition time probably is within the `MASTER` paramset. I don't think there's any other way to do this other than first setting the time and then turn on the light in two separate steps. Which will result in a terrible delay.

Can you be more specific about a device you want this for? I can have a look at the paramsets so we can figure out how you set the transition time in case you still want to do that.

**Comment by trilu2000** [comment]
Unfortunately you cannot set ramp_time and level within one putparamset message, at least the ramp_time is ignored :-)
In the homematic wireless protocol you can create a string to set the level and ramp_time within one string - but this type of message is not available via the RPC interface. 
The only workarround is to split the message in two setValue RPC calls.
In fhem it is pretty much similar handled: https://forum.fhem.de/index.php?topic=41060.60
So the idea would be - if there is a light.turn_on raised, pyhomematic checks the message for an transition time attribute, if there is one it sends first the setvalue for ramp_time and another setvalue for the level attribute. 
I didn't know to much about the pyhomematic interface and how the message handling works, so my hope was that it takes not too much efforts for you to implement.

**Comment by danielperna84** [comment]
I still think this is already possible to do manually. What they do in FHEM can be done like this:

```yaml
script:
  light_on_slow:
    sequence:
      - service: homematic.set_device_value
        data:
          address: LEQ123456
          channel: 1
          param: ON_TIME
          value: x
      - service: homematic.set_device_value
        data:
          address: LEQ123456
          channel: 1
          param: RAMP_TIME
          value: y
      - service: homematic.set_device_value
        data:
          address: LEQ123456
          channel: 1
          param: LEVEL
          value: z
```

On the API level this will probably do exactly the same as what that FHEM module does. If you want the light-service of Home Assistant to directly support this as an attribute of the service, you would have to add something roughly like this to [light.py](https://github.com/home-assistant/home-assistant/blob/2b490e44862ca7daae113fff092202ce9a646823/homeassistant/components/homematic/light.py#L80):

```python
# Put those globals at the top of the file where the other globals are
ATTR_ON_TIME = 'on_time'
ATTR_RAMP_TIME = 'ramp_time'
ATTR_HM_ON_TIME = 'ON_TIME'
ATTR_HM_RAMP_TIME = 'RAMP_TIME'
...
...
...
# At line 80 (before the first if) put this
if ATTR_ON_TIME in kwargs:
    self._hmdevice.setValue(ATTR_HM_ON_TIME, kwargs[ATTR_ON_TIME])
if ATTR_RAMP_TIME in kwargs:
    self._hmdevice.setValue(ATTR_HM_RAMP_TIME, kwargs[ATTR_RAMP_TIME])
```

You then could to something similar for the turn off service. And if all this works and you do a PR for Home Assistant, you should probably import [ATTR_TRANSITION](https://github.com/home-assistant/home-assistant/blob/2b490e44862ca7daae113fff092202ce9a646823/homeassistant/components/light/__init__.py#L45) and use that instead of `ATTR_RAMP_TIME`.

In general I don't get why they use `ON_TIME` in FHEM. To my knowledge that controls when the light will turn off again. In my opinion that's a second service call that just turns off the light. But anyways, the code snippet from above could work, and you could also implement other parameters like `OLD_LEVEL` or `RAMP_STOP` if that's somehow useful.
