### ISSUE TITLE
Exception: could not convert string to float

### ISSUE THREAD

**Issue by dm82m** [danielperna84/pyhomematic#237]
**Home Assistant version (if applicable):**
0.9.2

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml
homematic:
  interfaces:
    ip:
      host: ccu3-webui
      port: 2010
      resolvenames: json
  hosts:
    ccu3:
      host: ccu3-webui
      username: Admin
      password: !secret main_password
```

**Describe the bug**
I get a warning message every few minutes:
`2019-04-06 20:09:38 WARNING (Thread-5) [pyhomematic._hm] ServerThread.getAllSystemVariables: Exception: could not convert string to float: 
2019-04-06 20:19:32 WARNING (Thread-9) [pyhomematic._hm] ServerThread.getAllSystemVariables: Exception: could not convert string to float: 
2019-04-06 20:20:03 WARNING (Thread-11) [pyhomematic._hm] ServerThread.getAllSystemVariables: Exception: could not convert string to float: 
2019-04-06 20:20:34 WARNING (Thread-17) [pyhomematic._hm] ServerThread.getAllSystemVariables: Exception: could not convert string to float: 
2019-04-06 20:21:05 WARNING (Thread-12) [pyhomematic._hm] ServerThread.getAllSystemVariables: Exception: could not convert string to float: 
2019-04-06 20:21:36 WARNING (Thread-7) [pyhomematic._hm] ServerThread.getAllSystemVariables: Exception: could not convert string to float: 
`

**To Reproduce**
Just look into the HA log file.

**Expected behavior**
No warning message.
