### ISSUE TITLE
Jsonrpc Port ignored

### ISSUE THREAD

**Issue by wildi1** [danielperna84/pyhomematic#331]
**Home Assistant version (if applicable):**
0.115.2

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml
homematic:
  local_ip: xxx.xxx.xxx.xxx
  local_port: 20000
  interfaces:
    Funk:
      host: xxx.xxx.xxx.xxx
      port: 18001
      callback_ip: xxx.xxx.xxx.xxx
      callback_port: 20000
      resolvenames: xml
      jsonport: 18000
      username: Admin
      password: !secret
  hosts:
    ccu3:
      host: xxx.xxx.xxx.xxx
      port: 18001
      username: Admin
      password: !secret
```
**Describe the bug**
Parameter jsonport is ignored => ERROR (SyncWorker_4) [pyhomematic._hm] RPCFunctions.jsonRpcPost: Exception: <urlopen error [Errno 111] Connection refused>

**To Reproduce**
1. When Homematic is listening e.g. port 18000 you are unable to connect

**Expected behavior**
It should connect 

**Additional context**
I'm Running my homematic offshore behind an LTE Router, so i have build up a bidirectional ssh tunnel because of the missing public ip. In my case I map the port 18000 to homematics port 80 but the connection does not work. In following logfile you can see, that port 80 instead of 18000 is used.

**Logfile**
2020-09-23 22:55:35 DEBUG (SyncWorker_12) [pyhomematic._hm] RPCFunctions.jsonRpcPost: API-Endpoint: http://xxx.xxx.xxx.xxx:80/api/homematic.cgi
2020-09-23 22:55:35 ERROR (SyncWorker_12) [pyhomematic._hm] RPCFunctions.jsonRpcPost: Exception: <urlopen error [Errno 111] Connection refused>
2020-09-23 22:55:35 WARNING (SyncWorker_12) [pyhomematic._hm] ServerThread.jsonRpcLogin: Unable to open session.

**Comment by danielperna84** [comment]
I don't see why it's not working. The HA-component supports the parameter ([here](https://github.com/home-assistant/core/blob/576fbbe0be3b684618e453fc0bce1809673663cd/homeassistant/components/homematic/__init__.py#L222)), and in pyhomematic we even switch to https in case of port `443` [here](https://github.com/danielperna84/pyhomematic/blob/0944b85462d34c8dbaa995ae6788e106c3b4683b/pyhomematic/_hm.py#L369). So it _should_ work. 🤔

**Comment by wildi1** [comment]
Thank you for your answer. The resolvenames option setted to xml was just another try. I had it to json before, but posted my last config here. It was bit late:-)

Can you reproduce the behaviour I descriped on your own by setting a different jsonport? Or does it work to you?

**Comment by hanzoh** [comment]
I added the jsonport functionality back then when I played with running CCU in a Docker container.
As that was unstable, I moved to RaspberryMatic running in a VM.
But as RaspberryMatic is now available as a Docker container (still WIP), I gave it another try.

I can confirm, that the jsonport config entry is not honored:

```txt
2021-01-07 11:32:37 DEBUG (SyncWorker_14) [pyhomematic._hm] ServerThread.getAllSystemVariables: Getting all System variables via JSON-RPC
2021-01-07 11:32:37 DEBUG (SyncWorker_14) [pyhomematic._hm] RPCFunctions.jsonRpcPost: Method: Session.login
2021-01-07 11:32:37 DEBUG (SyncWorker_14) [pyhomematic._hm] RPCFunctions.jsonRpcPost: API-Endpoint: http://192.168.1.10:80/api/homematic.cgi
2021-01-07 11:32:37 ERROR (SyncWorker_14) [pyhomematic._hm] RPCFunctions.jsonRpcPost: Exception: HTTP Error 308: Permanent Redirect
2021-01-07 11:32:37 WARNING (SyncWorker_14) [pyhomematic._hm] ServerThread.jsonRpcLogin: Unable to open session.
```

```yaml
homematic:
  interfaces:
    ip:
      host: 192.168.1.10
      port: 2010
      resolvenames: json
      jsonport: 8082
      username: Admin
      password: x
    groups:
      host: 192.168.1.10
      port: 9292
      resolvenames: json
      jsonport: 8082
      username: Admin
      password: x
      path: /groups
  hosts:
    ccu:
      host: 192.168.1.10
      port: 2001
      username: Admin
      password: x
```
