### ISSUE TITLE
Use "port" option of home assistant instead of "jsonport" option for "hosts"

### ISSUE THREAD

**Issue by wladwnt** [danielperna84/pyhomematic#355]
Home Assistant version: 0.118.3

Setup: Homeassistant, debmatic with WEB User Interface on Port 8888 (instead of standart port 80)

configuration.yaml:
```yaml
homematic:
  interfaces:
    ip:
      host: 127.0.0.1
      port: 2010
      jsonport: 8888
      username: Admin
      password: xxxx
    groups:
      host: 127.0.0.1
      port: 9292
      jsonport: 8888
      username: Admin
      password: xxxx
      path: /groups
  hosts:
    ccu3:
      host: 127.0.0.1
      port: 8888
      username: Admin
      password: xxxx
```
relevant log details from home assistant:
```
Logger: pyhomematic._hm
Source: /usr/local/lib/python3.8/site-packages/pyhomematic/_hm.py:753
First occurred: 16:01:39 (4 occurrences)
Last logged: 16:03:09
ServerThread.jsonRpcLogin: Unable to open session. 
```
```
Logger: pyhomematic._hm
Source: /usr/local/lib/python3.8/site-packages/pyhomematic/_hm.py:387
First occurred: 16:01:39 (4 occurrences)
Last logged: 16:03:09
RPCFunctions.jsonRpcPost: Exception: HTTP Error 404: Not Found 
```
```
Logger: pyhomematic._hm
Source: /usr/local/lib/python3.8/site-packages/pyhomematic/_hm.py:672
First occurred: 16:01:39 (1 occurrences)
Last logged: 16:01:39
Skipping init for homeassistant-ccu3 
```
My understanding of the problem: pyhomematic tries to make jsonrpc connection to CCU on default JSON port (defined as DEFAULT_JSONPORT = 80 in "_hm.py"). But I run CCU WEB User Interface on port 8888. Since Home Assistant'a Homematic component does not have "jsonport" option for "hosts:" section (only for "interfaces:"), I cannnot change this standart port 80 for "ccu3" host to any other. I only can set "port" option to 8888. The correct solution must be probably that pyhomematic should use there (for hosts) "port" option of home asisstant homematic component instead of "jsonport" option.
As a result "ccu3" component is not available in home assistant.

The Problem does not exist (and ccu3 component appears in HA) if I run debmatic's OCCU on standart port (80) and use in options above 80 instead of 8888.
