### ISSUE TITLE
Service homematic.set_device_value works badly with HmIP-SMO

### ISSUE THREAD

**Issue by Plazmin** [danielperna84/pyhomematic#422]
I run the latest version of pyhomematic and Home Assistant.

```yaml
service: homematic.set_device_value
data:
  address: 00095BE99CC76D
  param: MOTION_DETECTION_ACTIVE
  interface: ip_ccu3_2
  value: 'True'
  channel: 1
  value_type: boolean
```

```yaml
service: homematic.set_device_value
data:
  address: 00095BE99CC76D
  param: MOTION_DETECTION_ACTIVE
  interface: ip_ccu3_2
  value: 'False'
  channel: 1
  value_type: boolean
```

**Describe the bug**
I am trying to set the state of the MOTION_DETECTION_ACTIVE variable with this service. Everything works fine if I set the state of the variable from False to True. However, when you try to change from True to False, the state does not change. Setting a variable using the CCU3 GUI works fine. There are no errors in the logs. I  don't know where the problem is :(

**Screenshots**
![smo](https://user-images.githubusercontent.com/62091912/126081995-03234e8e-c054-42b3-a249-daefe4b3654c.png)

**Comment by danielperna84** [comment]
You are sending the strings `'True'` and `'false'`. As both are none-empty strings, the CCU views them as a boolean `True`. Try it like this:

```yaml
service: homematic.set_device_value
data:
  address: 00095BE99CC76D
  param: MOTION_DETECTION_ACTIVE
  interface: ip_ccu3_2
  value: false
  channel: 1
  value_type: boolean
```
