### ISSUE TITLE
HM-ES-TX-WM not compatible with Home Assistant‘s new energy dashboard - Sensor not shown due to long term statistics implementation

### ISSUE THREAD

**Issue by simonszu** [danielperna84/pyhomematic#430]
**Home Assistant version (if applicable):**
2021.9.1

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml
local_port: 8060
interfaces:
  default:
    host: 192.168.12.10
    port: 2001
    callback_ip: 192.168.10.4
    callback_port: 8060
```

Use the following configuration for debug-output of the related components:
```yaml
logs:
  homeassistant.components.homematic: debug
  pyhomematic: debug
```

**Describe the bug**
I am using a HM-ES-TX-WM with an ES-IEC sensor to get some values out of my smart meter. The integration returns a power value (how much power i am currently consuming) and an energy value (the value of the smart meter counter). For integrating the sensor values into the new energy dashboard, Home Assistant needs a energy value type sensor, which is theoretically provided by the integration in a native way. However, the energy sensor provided by the integration is not shown in the dropdown list for selection, and Home Assistant suggests to open an issue for the integration about long term statistics (https://www.home-assistant.io/more-info/statistics/ and https://developers.home-assistant.io/docs/core/entity/sensor/) which i am doing right now. 

**To Reproduce**
1. Go to Settings
2. Go to Energy Section
3. Click on „Grid Consumption -> Add consumption“
4. Try to select the sensor with the suffix „_iec_energy_counter“
5. 
**Expected behavior**
The sensor should appear in the list and be selectable

**Additional context**
A possible root cause could be: The sensor returns the value of the meter in unit type Wh and the dropdown list expects the unit to be in kWh. Maybe it would be sufficient to change the unit integration-wide, since the actual value which is read is in kWh nevertheless. This could be handled in another issue, though, but it did not bother me until now. 
Just creating a customization for the sensor to change its unit type to kWh is not enough, it seems, so its most probably not enough.
