### ISSUE TITLE
Please add "HmIP-SMO-2" (color white), which is identical to "HmIP-SMO-A" (color black)

### ISSUE THREAD

**Issue by greewoo** [danielperna84/pyhomematic#453]
**Home Assistant version (if applicable):**
2021.12.5

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```
homematic:
  local_ip: !secret homematic_IP_local
  local_port: 36845
  interfaces:
    ip:
      host: !secret homematic_IP_host
      port: 2010
      callback_ip: !secret homematic_IP_local
      callback_port: 36845
      username: !secret homematic_Username
      password: !secret homematic_Password
      resolvenames: "json"
    groups:
      host: !secret homematic_IP_host
      port: 9292
      resolvenames: "json"
      username: !secret homematic_Username
      password: !secret homematic_Password
      path: /groups
  hosts:
    ccu2:
      host: !secret homematic_IP_host
      port: 2001
      username: !secret homematic_Username
      password: !secret homematic_Password
```

**Describe the bug**
I added 2 Motion Detection to my home.

The "HmIP-SMO-A" (color black) which is recognized in Home Assistant and the "HmIP-SMO-2" (color white) which is not recognized. 

Both are technical identical. They just have housings in different colors. 

**Expected behavior**
Both are recognized in HA.

**Additional context**
pyhomematic/devicetypes/sensors.py
```
    "HmIP-SMO": MotionIP, 
    "HmIP-SMO-A": MotionIP,
```
 _"HmIP-SMO-2": MotionIP,_ <- Please Add

Homematic JSON:
```
<device name='yyy1' address='xxx1' ise_id='6609' interface='HmIP-RF' device_type='HmIP-SMO-A' ready_config='true'>

<device name='yyy2' address='xxx2' ise_id='6574' interface='HmIP-RF' device_type='HmIP-SMO-2' ready_config='true'>
```
