### ISSUE TITLE
homeassistant loses the connection to homegear

### ISSUE THREAD

**Issue by crabmanX** [danielperna84/pyhomematic#66]
**Description of problem:**

I am running the latest homeassistant (version 0.43.2) docker on my NAS (192.168.1.23) and homegear (version 0.6.20-987) on an rpi (192.168.1.31) with HM-MOD-RPI-PCB module. After a few days, homeassistant loses the connection to homegear, so that sensors are not updated anymore and changes made in HA are not propagated to my homematic devices.

the docker container is run with:
```bash
/usr/bin/docker run \
    --name=home-assistant \
    --net=host \
    --expose 8123 \
    -v /var/lib/docker-confs/home-assistant:/config \
    -v /etc/localtime:/etc/localtime:ro \
    --device=/dev/ttyUSB0:/mysensorsgw:rwm \
    homeassistant/home-assistant
```

The problem is reproducible but it usually takes a few days until the connection is lost. The last temperature value was logged at 11:59 on the 2017-04-28.

I attched the last few lines from homegear.err, the output of "grep "04/28/17" /var/log/homegear/homegear.log | grep RPC" between 11:00 and 13:00, and the output of "grep homematic  home-assistant.log | grep -v "websocket_api", also between 11:00 and 13:00 (it seems like the last entry is from 12:05:59 though).

(removed logfiles)

**Home Assistant version (if applicable):**
0.43.2

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml
homematic:
  local_ip: 192.168.1.23
  local_port: 34279
  hosts:
    wireless:
      ip: 192.168.1.31
      resolvenames: metadata

logger:
    logs:
        homeassistant.components.homematic: debug
        pyhomematic: debug
```

Let me know if you need anything else!
